name: Build LaTeX document
on: [push]
permissions:
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
      - name: Check if PDF was generated
        run: |
          if [ ! -f cv.pdf ]; then
            echo "PDF was not generated."
            exit 1
          fi
      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: cv.pdf
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: -7
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: cv compiled on ${{ steps.time.outputs.time }}
          tag_name: ${{ steps.time.outputs.time }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cv.pdf
          asset_name: cv-${{ steps.time.outputs.time }}.pdf
          asset_content_type: application/pdf
      - name: Install ghostscript
        run: sudo apt-get update --fix-missing && sudo apt install ghostscript
      - name: Increase ImageMagick cache limit
        run: |
          sudo sed -i 's/<policy domain="resource" name="memory" value="256MiB"\/>/<policy domain="resource" name="memory" value="2GiB"\/>/' /etc/ImageMagick-6/policy.xml
          sudo sed -i 's/<policy domain="resource" name="map" value="512MiB"\/>/<policy domain="resource" name="map" value="4GiB"\/>/' /etc/ImageMagick-6/policy.xml
      - name: Change ImageMagick security policy for PDF
        run: |
          sudo sed -i 's|<policy domain="coder" rights="none" pattern=\"PDF\" />|<policy domain="coder" rights="read|write" pattern=\"PDF\" />|' /etc/ImageMagick-6/policy.xml
      - name: Convert PDF to PNG
        run: convert -density 300 -background white -alpha off cv.pdf -resize 25% -quality 90 -colorspace RGB cv.png
      - name: Commit PNG
        id: commit
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add cv.png
          git commit -m "[bot] updated cv.png"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
